config_settings = {
    'rand': True,
    'random_state': 100,
    'split_ratio': 0.8,
    'support_size': 15,
    'query_size': 5,
    'embedding_dim': 100,
    'n_layer': 2,
    'alpha': 0.5,
    'beta': 0.05,
    'gamma': 0.1,
    'rho': 0.01,
    'lamda': 0.05,
    'tao': 0.01,
    'n_k': 1,
    'batch_size': 5,
    'n_epoch': 1,
    'n_inner_loop': 1,
    'active_func': 'sigmoid',
    'cuda_option': 'cuda:0'
}
